# Project Context - memento

## Project Identity
name: memento
description: Session persistence plugin for Claude Code - persist context across conversation resets with branch-based session tracking
domain: devtools, claude-code-plugin

## Technology Stack
language: javascript
runtime: node.js
infrastructure: local (Claude Code plugin)

## Architecture Patterns
patterns: file-based-persistence, hook-driven
structure: claude-code-plugin

## Conventions
naming:
  files: kebab-case
  functions: camelCase
  constants: SCREAMING_SNAKE_CASE

testing:
  framework: node:test (built-in)
  style: AAA (arrange-act-assert)
  location: tools/__tests__/

## Commands
test: npm test
test:watch: npm run test:watch

## Key Directories
tools: session management scripts (create-session.js, get-session.js, session.js)
templates: session templates for different work types (feature.md, fix.md, chore.md)
commands: slash command definitions (session.md, init.md)
hooks: startup hooks (hooks.json references tools/)
context: context files for mantra integration (sessions.yml, sessions.md)
.claude-plugin: plugin manifest files (plugin.json, marketplace.json)

## Domain Terminology
session: a markdown file tracking work state for a specific branch/issue
branch-metadata: compact file mapping current git branch to its session file
session-template: predefined structure (feature, fix, chore) for new sessions
mantra: sibling plugin for periodic context refresh
onus: sibling plugin for work-item/issue integration

## Plugin Architecture
# This is a Claude Code plugin following the plugin specification
# Key files:
#   .claude-plugin/plugin.json - plugin manifest
#   hooks/hooks.json - hook definitions
#   commands/*.md - slash command prompts
#   tools/*.js - executable scripts
#   context/*.yml - context files for mantra

## Session Workflow
# 1 Session = 1 Issue = 1 Branch
# Branch naming: type/scope-number/description
# Session file: .claude/sessions/{branch-sanitized}.md
# Branch metadata: .claude/branches/{branch-slug}
