# Plugin Project Overview - Compact Reference

name: claude-domestique
type: claude-code-plugin
purpose: strategic-coding-partner (workflow-management, skeptical-assessment, session-persistence)
metaphor: cycling-domestique (carries-water, stays-focused, does-unglamorous-work)
repository: github.com/flexion/claude-domestique (planned)
work-tracking: github-issues

tech-stack:
  artifacts: markdown (commands, agents, skills), bash (scripts, hooks), json (manifest, schemas)
  no-programming-language: plugin-definitions-only
  validation: integration-testing (install in test projects)

structure:
  commands: slash-commands (next, create-session, update-session, check, refresh, new-work)
  agents: specialized-agents (session-manager, git-workflow)
  skills: auto-invoke-capabilities (context-loader, session-detector, test-runner, checklist-matcher)
  hooks: workflow-enforcement (pre-commit, pre-pr, prompt-submit)
  scripts: utilities (get-current-session.sh, create-branch-metadata.sh, run-tests.sh, config-reader.sh)
  templates: context-templates (.yml.template), work-item-templates (github, azure-devops)
  docs: installation, configuration, commands, migration

development-workflow:
  phase-0: bootstrap (copy .claude from simple-D365, customize for plugin dev)
  phase-1-6: use-bootstrap (develop plugin using copied workflow)
  transition: self-host (install plugin in own repo, migrate bootstrap setup)
  ongoing: dogfood (use plugin to develop itself, improve through usage)

test-projects:
  simple-D365: typescript-node, github, terraform
  Portal-D365-WebApp: react-typescript, azure-devops, frontend-last
  portal-D365: java-spring, azure-devops, expand-contract

universal-patterns: sessions, git-discipline, behavior-assessment, testing-philosophy, context-loading
configurable-patterns: test-commands, build-tools, work-item-systems, deployment-strategies, tech-stack-specifics

dogfooding: true (after phase-5-migration-tools-complete)
release-target: v1.0.0 (all-phases-complete, tested-in-3-projects, docs-complete)
