# mantra Project Context

## Identity
name: mantra
tagline: "I told you. You agreed. You forgot. Repeat."
purpose: periodic context refresh plugin for Claude Code sessions
problem: Claude drifts from guidance as context window fills

## Architecture
type: hook (UserPromptSubmit + SessionStart)
runtime: node (cross-platform, Claude Code prerequisite)
language: javascript
config: .claude/config.json (context.periodicRefresh.interval)

## Core Concepts
context-drift: Claude gradually forgets guidance over long sessions
context-refresh: re-inject key files to reinforce behavior
context-freshness: visible indicator of how stale context is
mantra: repeated phrase to focus the mind (Claude's mind wanders, this brings it back)

## Context Structure
location: .claude/context/
format-compact: *.yml (machine-optimized, token-efficient)
format-verbose: *.md (human-readable, detailed examples)
two-tier: yml for assertions, md for elaboration

## Design Principles
unobtrusive: minimal interference with actual work
narrow-scope: do one thing well (context refresh)
fast-refresh: quick injection, obvious acknowledgment
token-aware: don't overwhelm context with reinforcement
cross-platform: node-based tooling

## Requirements (from ideas.txt)
- configurable refresh intervals (turn count, token threshold, on-demand)
- selective file targeting (refresh specific files, not entire codebase)
- lightweight injection (summaries or full files)
- works with CLAUDE.md, project docs, custom instruction files
- context freshness indicator (drift detector for user)
- dog-food on this project when mature

## v1 Scope (implemented)
- turn-count refresh (configurable via .claude/config.json)
- context freshness indicator (every prompt)
- session-start injection
- yml-only injection (md for humans)
- CLAUDE.md fallback

## Deferred (out of scope for v1)
- on-demand refresh trigger
- token-threshold refresh
- multi-plugin orchestration (belongs in claude-domestique)

## Related Projects
parent: claude-domestique (full workflow system)
upstream: https://github.com/flexion/claude-domestique/tree/main/mantra.git
